{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noccounting.secretName" . }}
  labels:
    {{- include "noccounting.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.config.telegramBotToken | quote }}
  NOTION_TOKEN: {{ .Values.config.notionToken | quote }}
  NOTION_DATABASE_ID: {{ .Values.config.notionDatabaseID | quote }}
  USER_MAPPING: {{ .Values.config.userMapping | quote }}
{{- end }}
