// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package domain

import (
	"fmt"
	"strings"
)

const (
	// CategoryFood is a Category of type food.
	CategoryFood Category = "food"
	// CategoryTransport is a Category of type transport.
	CategoryTransport Category = "transport"
	// CategoryShopping is a Category of type shopping.
	CategoryShopping Category = "shopping"
	// CategoryActivities is a Category of type activities.
	CategoryActivities Category = "activities"
	// CategoryAccommodation is a Category of type accommodation.
	CategoryAccommodation Category = "accommodation"
	// CategorySightseeing is a Category of type sightseeing.
	CategorySightseeing Category = "sightseeing"
	// CategoryGroceries is a Category of type groceries.
	CategoryGroceries Category = "groceries"
	// CategoryFlights is a Category of type flights.
	CategoryFlights Category = "flights"
	// CategoryFuel is a Category of type fuel.
	CategoryFuel Category = "fuel"
	// CategoryParking is a Category of type parking.
	CategoryParking Category = "parking"
	// CategoryFees is a Category of type fees.
	CategoryFees Category = "fees"
	// CategoryHealth is a Category of type health.
	CategoryHealth Category = "health"
	// CategoryTips is a Category of type tips.
	CategoryTips Category = "tips"
	// CategoryOther is a Category of type other.
	CategoryOther Category = "other"
)

var ErrInvalidCategory = fmt.Errorf("not a valid Category, try [%s]", strings.Join(_CategoryNames, ", "))

var _CategoryNames = []string{
	string(CategoryFood),
	string(CategoryTransport),
	string(CategoryShopping),
	string(CategoryActivities),
	string(CategoryAccommodation),
	string(CategorySightseeing),
	string(CategoryGroceries),
	string(CategoryFlights),
	string(CategoryFuel),
	string(CategoryParking),
	string(CategoryFees),
	string(CategoryHealth),
	string(CategoryTips),
	string(CategoryOther),
}

// CategoryNames returns a list of possible string values of Category.
func CategoryNames() []string {
	tmp := make([]string, len(_CategoryNames))
	copy(tmp, _CategoryNames)
	return tmp
}

// CategoryValues returns a list of the values for Category
func CategoryValues() []Category {
	return []Category{
		CategoryFood,
		CategoryTransport,
		CategoryShopping,
		CategoryActivities,
		CategoryAccommodation,
		CategorySightseeing,
		CategoryGroceries,
		CategoryFlights,
		CategoryFuel,
		CategoryParking,
		CategoryFees,
		CategoryHealth,
		CategoryTips,
		CategoryOther,
	}
}

// String implements the Stringer interface.
func (x Category) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Category) IsValid() bool {
	_, err := ParseCategory(string(x))
	return err == nil
}

var _CategoryValue = map[string]Category{
	"food":          CategoryFood,
	"transport":     CategoryTransport,
	"shopping":      CategoryShopping,
	"activities":    CategoryActivities,
	"accommodation": CategoryAccommodation,
	"sightseeing":   CategorySightseeing,
	"groceries":     CategoryGroceries,
	"flights":       CategoryFlights,
	"fuel":          CategoryFuel,
	"parking":       CategoryParking,
	"fees":          CategoryFees,
	"health":        CategoryHealth,
	"tips":          CategoryTips,
	"other":         CategoryOther,
}

// ParseCategory attempts to convert a string to a Category.
func ParseCategory(name string) (Category, error) {
	if x, ok := _CategoryValue[name]; ok {
		return x, nil
	}
	return Category(""), fmt.Errorf("%s is %w", name, ErrInvalidCategory)
}

// MarshalText implements the text marshaller method.
func (x Category) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Category) UnmarshalText(text []byte) error {
	tmp, err := ParseCategory(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Category) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// CurrencyTWD is a Currency of type TWD.
	CurrencyTWD Currency = "TWD"
	// CurrencyJPY is a Currency of type JPY.
	CurrencyJPY Currency = "JPY"
)

var ErrInvalidCurrency = fmt.Errorf("not a valid Currency, try [%s]", strings.Join(_CurrencyNames, ", "))

var _CurrencyNames = []string{
	string(CurrencyTWD),
	string(CurrencyJPY),
}

// CurrencyNames returns a list of possible string values of Currency.
func CurrencyNames() []string {
	tmp := make([]string, len(_CurrencyNames))
	copy(tmp, _CurrencyNames)
	return tmp
}

// CurrencyValues returns a list of the values for Currency
func CurrencyValues() []Currency {
	return []Currency{
		CurrencyTWD,
		CurrencyJPY,
	}
}

// String implements the Stringer interface.
func (x Currency) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Currency) IsValid() bool {
	_, err := ParseCurrency(string(x))
	return err == nil
}

var _CurrencyValue = map[string]Currency{
	"TWD": CurrencyTWD,
	"JPY": CurrencyJPY,
}

// ParseCurrency attempts to convert a string to a Currency.
func ParseCurrency(name string) (Currency, error) {
	if x, ok := _CurrencyValue[name]; ok {
		return x, nil
	}
	return Currency(""), fmt.Errorf("%s is %w", name, ErrInvalidCurrency)
}

// MarshalText implements the text marshaller method.
func (x Currency) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Currency) UnmarshalText(text []byte) error {
	tmp, err := ParseCurrency(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Currency) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// PaymentMethodCash is a PaymentMethod of type cash.
	PaymentMethodCash PaymentMethod = "cash"
	// PaymentMethodCreditCard is a PaymentMethod of type credit_card.
	PaymentMethodCreditCard PaymentMethod = "credit_card"
	// PaymentMethodIcCard is a PaymentMethod of type ic_card.
	PaymentMethodIcCard PaymentMethod = "ic_card"
	// PaymentMethodEPay is a PaymentMethod of type e_pay.
	PaymentMethodEPay PaymentMethod = "e_pay"
)

var ErrInvalidPaymentMethod = fmt.Errorf("not a valid PaymentMethod, try [%s]", strings.Join(_PaymentMethodNames, ", "))

var _PaymentMethodNames = []string{
	string(PaymentMethodCash),
	string(PaymentMethodCreditCard),
	string(PaymentMethodIcCard),
	string(PaymentMethodEPay),
}

// PaymentMethodNames returns a list of possible string values of PaymentMethod.
func PaymentMethodNames() []string {
	tmp := make([]string, len(_PaymentMethodNames))
	copy(tmp, _PaymentMethodNames)
	return tmp
}

// PaymentMethodValues returns a list of the values for PaymentMethod
func PaymentMethodValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodCash,
		PaymentMethodCreditCard,
		PaymentMethodIcCard,
		PaymentMethodEPay,
	}
}

// String implements the Stringer interface.
func (x PaymentMethod) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PaymentMethod) IsValid() bool {
	_, err := ParsePaymentMethod(string(x))
	return err == nil
}

var _PaymentMethodValue = map[string]PaymentMethod{
	"cash":        PaymentMethodCash,
	"credit_card": PaymentMethodCreditCard,
	"ic_card":     PaymentMethodIcCard,
	"e_pay":       PaymentMethodEPay,
}

// ParsePaymentMethod attempts to convert a string to a PaymentMethod.
func ParsePaymentMethod(name string) (PaymentMethod, error) {
	if x, ok := _PaymentMethodValue[name]; ok {
		return x, nil
	}
	return PaymentMethod(""), fmt.Errorf("%s is %w", name, ErrInvalidPaymentMethod)
}

// MarshalText implements the text marshaller method.
func (x PaymentMethod) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *PaymentMethod) UnmarshalText(text []byte) error {
	tmp, err := ParsePaymentMethod(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *PaymentMethod) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
